name: deploy

on:
  push:
    branches:
      - main

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Test Build
        run: |
          npm ci --legacy-peer-deps
          npm run build
          
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Release to GitHub Pages
        env:
          GIT_USER: github-actions
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          npm ci --legacy-peer-deps
          npm run tailwind:css
          npx docusaurus deploy -- --token ${{ secrets.GITHUB_TOKEN }}
